为用户分配权限和表空间

-- QUOTAS
ALTER USER xiaoqingyu QUOTA UNLIMITED ON USERS;
ALTER USER xiaoqingyu QUOTA UNLIMITED ON USERS02;
ALTER USER xiaoqingyu QUOTA UNLIMITED ON USERS03;
ALTER USER xiaoqingyu ACCOUNT UNLOCK;

--roles
GRANT "CONNECT" TO xiaoqingyu WITH ADMIN OPTION;
GRANT "RESOURCE" TO xiaoqingyu WITH ADMIN OPTION;
ALTER USER xiaoqingyu DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO xiaoqingyu WITH ADMIN OPTION;